export const GET_DATA_ID='GET_DATA_ID'
export const GET_HOME_DATA='GET_HOME_DATA'

export const GET_ALL_READ='GET_ALL_READ'
export const GET_ALL_MOVIE='GET_ALL_MOVIE'
export const GET_ALL_MUSICM='GET_ALL_MUSICM'
export const GET_ALL_MUSIC='GET_ALL_MUSIC'

export const GET_ESSAY_DETAIL='GET_ESSAY_DETAIL'
export const GET_LONG_DETAIL='GET_LONG_DETAIL'
export const GET_QUE_DETAIL='GET_QUE_DETAIL'
export const GET_MUSIC_DETAIL='GET_MUSIC_DETAIL'
export const GET_MOVIE_DETAIL='GET_MOVIE_DETAIL'
export const GET_MUSICDATE_DETAIL='GET_MUSICDATE_DETAIL'